fn default_phases() -> Vec<WorkflowPhase> {
    vec![
        WorkflowPhase {
            id: "s0_admission",
            stage_id: "stage0",
            stage_code: "S0",
            title: "S0 admission and project index",
            gate: PhaseGate::S0Admission,
            hard_gate: false,
            contract: "Emit RUNBOOK% S0 Admission and one SERVICE_STATUS% marker. Verify source path, local target queue, service reachability, app scale, framework/tech hints, route count hints, and whether the target appears intentionally vulnerable or organically developed. Do not report vulnerabilities. S0 is not complete until SERVICE_STATUS% reachable, SERVICE_STATUS% started, or SERVICE_STATUS% blocked is emitted.",
            body: "Check the source tree and local or user-provided target with lightweight commands. Build a compact project index: language/framework, server entrypoint, route directories, frontend directory, config files, data stores, upload/file surfaces, auth/session primitives, and likely test credentials if source-visible. Emit BREADTH% with an initial scale guess. If the service is down and the objective authorized local starts, recover it in S0 rather than deferring to S4: start it with a durable background launcher, capture logs, poll the health URL until you get an actual HTTP response, and only then emit SERVICE_STATUS% started. If startup fails, inspect the startup log and emit SERVICE_STATUS% blocked with the reason instead of pretending the target is alive.",
        },
        WorkflowPhase {
            id: "s1_route_surface",
            stage_id: "stage1",
            stage_code: "S1",
            title: "S1 feature fingerprint and route/API boundary map",
            gate: PhaseGate::S1Surface,
            hard_gate: false,
            contract: "Emit RUNBOOK% S1 Recon plus a compact SURFACE%/OBLIGATION%/READ_TARGET% ledger for high-risk route, auth, object-id, middleware, schema/docs, and source/sink boundaries. This phase is invalid if it only says it will emit a ledger.",
            body: "Map network-reachable endpoints and route registration fast. Prefer rg, router tables, entrypoints, and file lists over broad cat of every handler. S1 is a security index for S2, not a generic route map: cover these five cheap global indexes before stopping: route_api_index, auth_session_jwt_index, object_ownership_index, source_sink_index, and config_docs_debug_index. Keep prose minimal: do not narrate routine planning with phrases like \"Let me\", \"I need\", or \"Now I\". Do not use marker names as Markdown headings; marker lines must be bare machine-readable lines. Marker field hygiene is mandatory: category=<single-taxonomy-token> only; put file/route in target/source/path, sink in sink, and short obligation name in debt. Never pack debt/source/sink/reason into category or target. Cover HTTP method/path, public/protected/admin hints, object identifiers, middleware, major request fields, API schemas/docs, helper utilities, support/dev routes, frontend routes that call backend APIs, and API paths mined from OpenAPI/Swagger/GraphQL/JavaScript bundles present in the source tree. Must-cover families for intentionally vulnerable web apps include login SQLi, JWT forge or algorithm confusion, basket/object ownership, password reset/change, 2FA/security question/CAPTCHA, file/key/log exposure, SSRF/redirect, XSS/browser sinks, wallet/coupon/deluxe/order/data export, and metrics/docs/config/secrets. SURFACE_BUDGET% stage=s1 total_max=90 route_phase_max=45 per_category_max=6 role=map_not_task. Emit SURFACE% only for representative backend state; use COVERAGE% for counts and inventories. READ_TARGET_BUDGET% stage=s1 total_max=25 route_phase_max=10 per_lane_max=5 priority=high_only. In this route/API phase, emit at most 10 READ_TARGET% lines total, no more than 5 for any lane, and do not emit medium/low priority read targets. A READ_TARGET% is an S2 deep-read work order, not a vulnerability conclusion or a checklist of every interesting file: lane=<identity_engine|injection_engine|ingress_engine|logic_engine|config_engine|any> priority=high category=<domain> kind=<endpoint-control|sink-trace|parser-boundary|business-invariant|config-baseline> path=<file-or-route> anchor=<function-or-symbol> reason=<why-this-file-is-first> question=<source-to-sink-or-invariant-to-prove> stop_when=<fact-that-closes-or-delegates> broaden_after=<named-gap-that-justifies-extra-rg> follow=<one-helper-or-model>. For OBLIGATION%, prefer id=<stable-id> category=<single-taxonomy-token> target=<route-or-file> debt=<short-name> source=<file:line> sink=<symbol-or-helper> must=<one-check>. Lane ownership: identity=auth/session/object ownership/IDOR; injection=SQL/NoSQL/template/eval/browser sinks; ingress=upload/parser/file/traversal/SSRF/redirect; logic=money/order/coupon/quota/workflow state transitions; config=secrets/crypto/config/docs/dependency exposure. Choose one primary lane for each READ_TARGET%; record adjacent concerns as OBLIGATION% instead of duplicate READ_TARGET% lines. Deduplicate by path+kind+category; if multiple routes share one file, emit one READ_TARGET% and mention representative endpoints in reason. For IDOR/authz, prefer READ_TARGET% lane=identity_engine kind=endpoint-control with endpoint, object_id, auth_hint, and ownership_hint=unknown when ownership is not obvious. If a topic is useful but below the READ_TARGET% budget, emit OBLIGATION% debt instead of another READ_TARGET%. If deeper semantics require many file reads or live auth state, emit OBLIGATION% debt for S2 instead of doing the full audit in S1.",
        },
        WorkflowPhase {
            id: "s1_source_sink",
            stage_id: "stage1",
            stage_code: "S1",
            title: "S1 source/sink/parser/egress and obligation map",
            gate: PhaseGate::S1Surface,
            hard_gate: false,
            contract: "Emit additional FEATURE%/SURFACE%/OBLIGATION%/READ_TARGET% and COVERAGE% markers for source-sink inventory. Include sinks even before deciding they are vulnerable. Do not create final findings.",
            body: "Sample the highest-risk source/sink families rather than exhaustively tracing every handler: raw SQL/NoSQL, eval/template/browser render, deserialization/XML/YAML, file read/write/path joins, zip extraction, upload handlers, outbound fetch/http clients, redirects, crypto/key handling, cookie/session/JWT code, logs/metrics/debug/docs/static directories, auth/account metadata endpoints, header/media/browser sinks, business workflow helpers, and helper-side policy checks such as middleware attachment, ownership checks, parser validators, or support routes. Re-check the five S2-feeding indexes before ending S1: route_api_index, auth_session_jwt_index, object_ownership_index, source_sink_index, and config_docs_debug_index. Keep prose minimal: do not narrate routine planning with phrases like \"Let me\", \"I need\", or \"Now I\". Do not use marker names as Markdown headings; marker lines must be bare machine-readable lines. Marker field hygiene is mandatory: category=<single-taxonomy-token> only; put file/route in target/source/path, sink in sink, and short obligation name in debt. Never pack debt/source/sink/reason into category or target. Convert this map into explicit OBLIGATION% markers grounded in generic CVE-prior families: authorization gaps, injection, parser abuse, traversal, SSRF, secrets exposure, weak crypto, and workflow abuse. Keep the must-cover families visible for S2 even when S1 does not prove them: login SQLi, JWT forge or algorithm confusion, basket/object ownership, password reset/change, 2FA/security question/CAPTCHA, file/key/log exposure, SSRF/redirect, XSS/browser sinks, wallet/coupon/deluxe/order/data export, and metrics/docs/config/secrets. SURFACE_BUDGET% stage=s1 total_max=90 source_sink_additional_max=45 per_category_max=6 role=map_not_task. READ_TARGET_BUDGET% stage=s1 total_max=25 source_sink_additional_max=15 per_lane_max=5 priority=high_only. Emit only additional high-priority READ_TARGET% lines that were not already emitted in the route/API S1 phase; deduplicate by path+kind+category and keep one representative anchor per vulnerability family. Promote a sink to READ_TARGET% only when it gives S2 a precise question, stop condition, and one next file to follow; otherwise emit OBLIGATION% debt. For OBLIGATION%, prefer id=<stable-id> category=<single-taxonomy-token> target=<route-or-file> debt=<short-name> source=<file:line> sink=<symbol-or-helper> must=<one-check>. Do not turn every sink into a READ_TARGET%; if a lane already has 5 high-priority read targets, route the remaining items to OBLIGATION% debt. Bias logic_engine READ_TARGET% toward state transitions and business invariants, not generic endpoint lists. S1 must not prove the vulnerability; it only schedules the next deep read. When sink depth is obvious but time-consuming, mark the obligation and hand the deep trace to S2 instead of finishing it in S1.",
        },
        WorkflowPhase {
            id: "s2_parallel_semantic_audit",
            stage_id: "stage2",
            stage_code: "S2",
            title: "S2 concurrent 6-lane candidate discovery",
            gate: PhaseGate::S2Lane,
            hard_gate: true,
            contract: "Emit RUNBOOK% S2 Audit: launching workflow-owned candidate discovery. The backend scheduler owns this phase: it starts five core child threads with bounded provider-friendly concurrency, records queued/running/retrying/done lane status, joins their CLAIM% ledgers, then starts one optional residual quick_hits_engine using the core claim output. The five core lanes are the hard gate; quick_hits_engine is a recall-recovery lane and must not block S3 if empty or failed. S2 emits candidate CLAIM% rows only; evidence, rejection, controls, verification, and final findings belong to S4/S5.",
            body: "The backend scheduler launches these core native child engines first: identity_engine, injection_engine, ingress_engine, logic_engine, and config_engine. Do not serialize the core engines in the root and do not do all five audits yourself. After the core lanes join, quick_hits_engine runs as a residual rg-first recovery sweep mapped back into the same taxonomy and should only emit missed high-yield CLAIM% rows. Child engines receive compact S1 READ_TARGET% and SOURCE_PACKET% inputs plus a small cross-lane weak-signal obligation packet. Each child engine reads assigned targets and emits only concise CLAIM% candidates. After the scheduler joins all S2 lanes, S3 consumes the claim pool for merge, clustering, and S4 verification planning.",
        },
        WorkflowPhase {
            id: "s3_merge_foa",
            stage_id: "stage3",
            stage_code: "S3",
            title: "S3 merge, FoA, and debt ledger",
            gate: PhaseGate::S3Merge,
            hard_gate: true,
            contract: "Emit RUNBOOK% S3 Summary before any S4 marker. S3 must merge duplicate claim families, list unresolved debt, preserve distinct root causes, and review backend CHAIN_CANDIDATE% synthesis. Do not emit the final report.",
            body: "Review the S2 CLAIM% pool plus any S1 source context needed for naming. Merge and cluster same-family claims only when root cause + route/sink + exploit primitive match. Keep distinct endpoints and distinct exploit primitives separate. Emit MERGE% or DUPLICATE% for material duplicates, CHAIN_CANDIDATE% only when claim families can realistically compose, and BREADTH% surfaces=<n> domains=<n> hypotheses=<n> scale=<tiny|small|medium|large|seeded_or_intentionally_vulnerable> note=<why>. Emit RUNBOOK% S3 Summary with unique claim families, unresolved hypothesis debt, and the S4 verification plan.",
        },
        WorkflowPhase {
            id: "s4_auth_authz_session_controls",
            stage_id: "stage4",
            stage_code: "S4",
            title: "S4 targeted controls for auth/authz/session",
            gate: PhaseGate::S4Probe,
            hard_gate: true,
            contract: "Emit RUNBOOK% S4 Fuzz. Blanket skip is forbidden. For every in-scope auth/authz/session/rate-limit claim family, emit PROBE% and CONTROL%, VERIFY%, REJECTED%, or S4_SKIP% id=<claim> reason=<source-backed reason>. Do not end the turn after saying you will run probes.",
            body: "Run targeted live probes and negative controls for auth bypass, password reset/change, security question, JWT/session/cookie, role/mass assignment, IDOR/BOLA, object ownership, admin gates, and rate limits. Controls should compare authorized vs unauthorized, own object vs foreign object, valid state vs invalid state, or baseline vs exploit payload. Your first useful output must be a tool call or a machine-readable PROBE%/CONTROL%/VERIFY%/S4_SKIP% ledger line; prose such as 'Let me run the probes' does not count. If tool execution is unavailable, emit per-claim S4_SKIP% with the source-backed reason and preserve the claim for S5 as needs-poc/source-backed.",
        },
        WorkflowPhase {
            id: "s4_injection_xss_controls",
            stage_id: "stage4",
            stage_code: "S4",
            title: "S4 targeted controls for injection/xss/eval",
            gate: PhaseGate::S4Probe,
            hard_gate: true,
            contract: "Emit RUNBOOK% S4 Fuzz and per-claim PROBE%/CONTROL%/VERIFY% lines. Do not call JSON reflection browser XSS without a render sink. Do not call timeout/503 full RCE without command execution proof. Do not end the turn after saying you will run probes.",
            body: "For SQL/NoSQL/template/command/eval/vm/XSS claims, run precise payload variants and negative controls: normal input vs injected predicate, escaped payload vs raw payload, sanitizer-enabled vs bypass candidate, rendered sink vs JSON-only response, DoS signal vs code execution. For matching CHAIN_CANDIDATE% entries, emit CHAIN_VERIFY% only after an isolated, reversible verification plan. Emit REJECTED% for blocked or overclaimed paths. Your first useful output must be a tool call or a machine-readable PROBE%/CONTROL%/VERIFY%/S4_SKIP% ledger line; prose such as 'Let me run the probes' does not count.",
        },
        WorkflowPhase {
            id: "s4_files_ssrf_business_controls",
            stage_id: "stage4",
            stage_code: "S4",
            title: "S4 targeted controls for files/SSRF/business/debug",
            gate: PhaseGate::S4Probe,
            hard_gate: true,
            contract: "Emit RUNBOOK% S4 Fuzz and per-claim evidence. Blanket 'source available so skip fuzz' is invalid. Heavy fuzz may be skipped only per claim with S4_SKIP% and evidence.",
            body: "Probe upload/parser/file/traversal/SSRF/redirect/business/secrets/debug/crypto claims. SSRF needs server-side fetch evidence or downgrade. File claims need path resolution/write/read evidence and blocked-path controls. Business logic needs legal workflow vs bypass workflow. Secrets/config exposure needs public reachability and impact. For chain verification, avoid state pollution: prefer disposable users, unique object ids, temp files, read-only probes, service snapshots, or explicit cleanup; if rollback is unsafe, emit S4_SKIP% with source-backed reason instead of mutating shared state. Emit controls and rejections aggressively. Your first useful output must be a tool call or a machine-readable PROBE%/CONTROL%/VERIFY%/S4_SKIP% ledger line; prose such as 'Let me run the probes' does not count.",
        },
        WorkflowPhase {
            id: "s4_regression_sweep",
            stage_id: "stage4",
            stage_code: "S4",
            title: "S4 regression sweep against broad family corpus",
            gate: PhaseGate::S4Probe,
            hard_gate: true,
            contract: "Emit RUNBOOK% S4 Fuzz. This is a breadth recovery sweep. For any high-value family not represented in the ledger, emit a late CANDIDATE%/CLAIM% plus PROBE%/CONTROL%, or REJECTED% with evidence.",
            body: "Compare the ledger against the broad family corpus in GLOBAL_CONTRACT. Look specifically for missed mass assignment, weak crypto/hash, hardcoded credentials/keys, exposed API/account-metadata records, 2FA secret storage, CAPTCHA/security-answer leakage, token/progress-code helpers, coupon/payment/order/review/feedback business abuse, upload MIME/null-byte/extension bypass, public docs/metrics/logs/config/files, robots/static manifests, Swagger/OpenAPI exposure, parser abuse, archive traversal, open redirect, SSRF, header/host/media/browser sinks, and CORS/header/rate limit issues. Also review CHAIN_CANDIDATE% entries for the top bridge paths only; do not enumerate every possible pair. Use it as a generic web application coverage checklist, not a target-specific answer set. Your first useful output must be a tool call or a machine-readable PROBE%/CONTROL%/VERIFY%/S4_SKIP% ledger line; prose such as 'Let me run the probes' does not count.",
        },
        WorkflowPhase {
            id: "s5_adjudication_report",
            stage_id: "stage5",
            stage_code: "S5",
            title: "S5 final adjudication and report",
            gate: PhaseGate::S5Adjudicate,
            hard_gate: true,
            contract: "Emit RUNBOOK% S5 Verify and canonical FINDING% entries only after dedupe. Use ADJUDICATE% only for material merge/drop/downgrade decisions. This is the only phase allowed to produce the final report.",
            body: "Perform final quality control without sacrificing recall. Merge only same root cause + same route/sink + same exploit primitive. Drop only claims that are duplicates, contradicted by controls, out of scope, placeholders, or clearly non-security observations. If a claim has a source/root-cause anchor and plausible exploit impact but lacks live proof, keep it as source-backed or needs-poc instead of deleting it. Do not publish blocked/rejected/weak_signal assessments, scanner-only rows, or missing-version/behavior CVE leads as vulnerabilities, and do not convert non-reportable notes into final findings. Do not discard an entire family solely because one payload path, one bypass attempt, or one chain step failed when the same root cause still supports a weaker honest finding. Label statuses honestly: publishable requires source/root cause, exploit proof, and negative control; verified/source-backed/needs-poc must not masquerade as weaponized. Then emit canonical FINDING% lines for all credible surviving families, not just the top/highest-confidence subset. Finish with the first concise markdown report. After this draft, the backend will launch one advisory S5 review agent and then return its REVIEW% comments to you for the final correction pass.",
        },
        WorkflowPhase {
            id: "s5_adversarial_review",
            stage_id: "stage5",
            stage_code: "S5",
            title: "S5 advisory review lane",
            gate: PhaseGate::S5Review,
            hard_gate: true,
            contract: "The backend scheduler opens exactly one workflow-owned reviewer thread after the draft final report. The reviewer must emit advisory REVIEW% comments and one REVIEW_REPORT% line, without rewriting the report.",
            body: "Spawn the final_report_review child lane. It reviews only the supplied S5 draft and runbook ledger for duplicate families, false positives, unsupported severity, ledger-supported omissions, and report clarity. It must not run tools, inspect source, perform fresh auditing, or rewrite the report. Its output is advisory input, not an automatic veto, for the root agent's final correction pass.",
        },
        WorkflowPhase {
            id: "s5_final_revision",
            stage_id: "stage5",
            stage_code: "S5",
            title: "S5 review-driven final revision",
            gate: PhaseGate::S5FinalRevision,
            hard_gate: true,
            contract: "Consume REVIEW_CONTEXT from the advisory review lane, critically apply supported corrections, and emit RUNBOOK% S5 Final Revision plus the corrected canonical FINDING% set. This phase is output-only: no tool calls and no fresh auditing.",
            body: "Read REVIEW_CONTEXT critically. Reviewer comments are advisory, not authoritative. Accept merge/drop only when the ledger proves same-family duplication, contradiction by controls, out-of-scope scope, placeholder content, or non-security impact. For missing live proof, weak payload, or unclear severity, prefer downgrade/rewrite/source-backed/needs-poc over deletion. Do not let a failed payload variant or failed alternate exploit chain erase a root family that is still source-backed and security-relevant. Preserve recall: every credible root family with source/root-cause anchor and plausible exploit impact must remain in the replacement FINDING% set with an honest status. If you reject a reviewer suggestion, state the reason briefly. Do not inspect source, run commands, or create new claims beyond REVIEW% action=add_check items that already cite runbook evidence. Emit REVIEW_APPLIED% target=<id-or-family> action=<accepted|rejected> reason=<short> for material comments. Then emit exactly one RUNBOOK% S5 Final Revision line, the corrected canonical FINDING% lines, and a concise final corrected markdown report. Treat this as a replacement final set, not an appendix to the draft.",
        },
    ]
}
